package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class GUIMainController {
	@FXML
	private Button btnServicio;
	@FXML
	private Button btnMecanico;
	@FXML
	private Button btnVehiculo;
	@FXML
	private Button btnCliente;
	@FXML
	private Button btnReporte;
	@FXML
	private Button btnOrden;

	// Event Listener on Button[#btnServicio].onAction
	@FXML
	public void servicio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnMecanico].onAction
	@FXML
	public void mecanico(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVehiculo].onAction
	@FXML
	public void vehiculo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCliente].onAction
	@FXML
	public void cliente(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIClient.fxml"));
			
			Parent root = loader.load();
			GUIClientController controller = loader.getController();
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			
			Stage temp = (Stage) this.btnCliente.getScene().getWindow();
			temp.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#btnReporte].onAction
	@FXML
	public void reporte(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnOrden].onAction
	@FXML
	public void ordenTrabajo(ActionEvent event) {
		// TODO Autogenerated
	}
}
