package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class GUIMainController {
	@FXML
	private Button btnServicio;
	@FXML
	private Button btnMecanico;
	@FXML
	private Button btnVehiculo;
	@FXML
	private Button btnCliente;
	@FXML
	private Button btnReporte;

	// Event Listener on Button[#btnServicio].onAction
	@FXML
	public void servicio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnMecanico].onAction
	@FXML
	public void mecanico(ActionEvent event) {
		
	}
	// Event Listener on Button[#btnVehiculo].onAction
	@FXML
	public void vehiculo(ActionEvent event) {
		MyUtils myUtils = new MyUtils();
		myUtils.changeView(btnVehiculo, "/presentation/GUIVehiculo.fxml", null);
	}
	// Event Listener on Button[#btnCliente].onAction
	@FXML
	public void cliente(ActionEvent event) {
		MyUtils myUtils = new MyUtils();
		myUtils.changeView(btnCliente, "/presentation/GUIClient.fxml", null);
	}
	// Event Listener on Button[#btnReporte].onAction
	@FXML
	public void reporte(ActionEvent event) {
		// TODO Autogenerated
	}
}