package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;

import javafx.scene.control.DatePicker;

public class GUIReportsController {
	@FXML
	private TextField tfVehiclePlate;
	@FXML
	private Button btnSearchVehicle;
	@FXML
	private Button btnClearVehicle;
	@FXML
	private TableView tvVehicleOrders;
	@FXML
	private Label lblTotalVehicle;
	@FXML
	private Label lblCostVehicle;
	@FXML
	private ComboBox cbMechanic;
	@FXML
	private ComboBox<String> cbStatus;
	@FXML
	private DatePicker dpStart;
	@FXML
	private DatePicker dpEnd;
	@FXML
	private Button btnSearchMechanic;
	@FXML
	private Button btnClearMechanic;
	@FXML
	private TableView tvMechanicOrders;
	@FXML
	private Label lblTotalMechanic;
	@FXML
	private Label lblCostMechanic;
	@FXML
	private TextField tfPlateHistory;
	@FXML
	private Button btnSearchHistory;
	@FXML
	private Button btnClearHistory;
	@FXML
	private TableView tvServiceHistory;
	@FXML
	private Label lblTotalServices;
	@FXML
	private Label lblTotalSpent;
	@FXML
	private Button btnInProcess;
	@FXML
	private Label lblResultProcess;
	@FXML
	private DatePicker dpRangeStart;
	@FXML
	private DatePicker dpRangeEnd;
	@FXML
	private Button btnSearchRange;
	@FXML
	private TextField tfMinAmount;
	@FXML
	private Button btnSearchAmount;
	@FXML
	private TableView tvAdvanced;
	@FXML
	private Button btnClearAdvanced;
	@FXML
	private Label lblInfoAdvanced;
	@FXML
	private Button btnReturn;

	// Event Listener on Button[#btnSearchVehicle].onAction
	@FXML
	public void searchOrdersVehicle(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnClearVehicle].onAction
	@FXML
	public void clearOrdersVehicle(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSearchMechanic].onAction
	@FXML
	public void searchOrdersMechanic(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnClearMechanic].onAction
	@FXML
	public void clearOrdersMechanic(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSearchHistory].onAction
	@FXML
	public void searchServiceHistory(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnClearHistory].onAction
	@FXML
	public void clearHistory(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnInProcess].onAction
	@FXML
	public void searchVehiclesInProcess(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSearchRange].onAction
	@FXML
	public void searchOrdersRange(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSearchAmount].onAction
	@FXML
	public void searchClientsAmount(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnClearAdvanced].onAction
	@FXML
	public void clearAdvancedSearch(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReturn].onAction
	@FXML
    public void returnHome(ActionEvent event) {
        MyUtils myUtils = new MyUtils();
        myUtils.changeView(btnReturn, "/presentation/GUIMain.fxml", null);
    }
}
